### PR TITLE
Fetch isobib

### PR DESCRIPTION
**Pull request by andrew2net**

### CODE REVIEW

**Comment by ronaldtse** [comment]
@andrew2net thanks for this -- after merging can asciidoctor-iso still work without an internet connection? Thanks.

**Comment by andrew2net** [comment]
@ronaldtse I didn't test it without an internet connection. I'll try.
Should asciidoctor-iso generates references as it did before implementing Isobib gem when an internet connection isn't available?

**Comment by ronaldtse** [comment]
Yes, it should fall back (and still generate the document) if no internet connection is available. It's hard to explain to people why it stops working without an internet connection.

**Comment by andrew2net** [comment]
@ronaldtse done rendering references without an Internet connection

**Comment by opoudjis** [comment]
Oh, sorry, you already did that. OK.

**Pull request merged**
